[2025-05-06 15:23:54] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:23:59] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:04] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:09] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:14] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:22] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:27] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:35] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:40] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:45] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:50] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:24:55] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:00] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:05] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:10] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:15] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:20] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:25] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:30] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:35] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:25:40] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'is_connected'
[2025-05-06 15:31:56] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: tcp_client_servive() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: tcp_client_servive() missing 1 required positional argument: 'client'
[2025-05-06 15:32:04] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:09] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:14] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:19] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:24] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:29] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:32:40] [ERROR] tcp_client_servive : 'bool' object has no attribute 'is_socket_open'
[2025-05-06 15:32:45] [ERROR] tcp_client_servive : 'bool' object has no attribute 'is_socket_open'
[2025-05-06 15:32:52] [ERROR] tcp_client_servive : name 'sock' is not defined
[2025-05-06 15:35:28] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:33] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:38] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:43] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:48] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:53] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:35:58] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:36:03] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:36:15] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:36:20] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:37:17] [ERROR] tcp_client_servive : 'LSIS_TcpClient' object has no attribute 'host'
[2025-05-06 15:39:45] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:39:45] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 65, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:39:50] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:39:50] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 65, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:39:55] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:39:55] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 65, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:00] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:00] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 65, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:10] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:10] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:15] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:15] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:20] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:20] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:33] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:33] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:38] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:38] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if sock:
       ^^^^
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[2025-05-06 15:40:45] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:45] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connected_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connected_sock:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connected_sock' where it is not associated with a value
[2025-05-06 15:40:50] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:50] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connected_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connected_sock:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connected_sock' where it is not associated with a value
[2025-05-06 15:40:55] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:40:55] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connected_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connected_sock:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connected_sock' where it is not associated with a value
[2025-05-06 15:41:00] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:00] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connected_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connected_sock:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connected_sock' where it is not associated with a value
[2025-05-06 15:41:07] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:07] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connect_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connect_sock:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connect_sock' where it is not associated with a value
[2025-05-06 15:41:12] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:12] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connect_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connect_sock:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connect_sock' where it is not associated with a value
[2025-05-06 15:41:17] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:17] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connect_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connect_sock:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connect_sock' where it is not associated with a value
[2025-05-06 15:41:22] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:22] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connect_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connect_sock:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connect_sock' where it is not associated with a value
[2025-05-06 15:41:27] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:27] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'connect_sock' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 66, in tcp_client_servive
    if connect_sock:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connect_sock' where it is not associated with a value
[2025-05-06 15:41:38] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:43] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:48] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:41:53] [ERROR] tcp_client_servive : cannot access local variable 'is_existed' where it is not associated with a value
[2025-05-06 15:47:50] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 15:47:55] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 15:55:20] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'retry_count'
[2025-05-06 15:55:31] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'retry_interval'
[2025-05-06 15:55:36] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'retry_interval'
[2025-05-06 15:55:45] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:55:50] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:55:55] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:56:00] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:56:05] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:56:10] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:56:15] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:56:20] [ERROR] tcp_client_servive : LSIS_TcpClient.connect() got an unexpected keyword argument 'timeout'
[2025-05-06 15:59:20] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:25] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:30] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:35] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:40] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:45] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 15:59:50] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:00:17] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:00:44] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:00:44] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:00:49] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:00:49] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:17] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:17] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:22] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:22] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:27] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:27] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:32] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:32] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:37] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:37] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:42] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:42] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:47] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:47] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:52] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:52] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:01:57] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:01:57] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:02] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:02] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:07] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:07] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:12] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:12] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:17] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:17] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:22] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:22] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:27] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:27] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:32] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:32] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:37] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:37] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:42] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:42] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:47] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:47] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:52] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:52] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:02:57] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:02:57] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:03:24] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:03:24] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:03:51] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:03:51] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:03:56] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:03:56] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:01] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:01] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:06] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:06] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:11] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:11] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:16] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:16] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:21] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:21] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:26] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:26] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:53] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:53] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:04:58] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:04:58] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:03] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:03] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:08] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:08] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:13] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:13] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:18] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:18] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:23] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:23] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:28] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:28] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:05:58] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:05:58] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:29] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:29] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:34] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:34] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:39] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:39] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:44] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:44] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:49] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:49] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:06:54] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:06:54] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:05] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:05] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:10] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:10] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:15] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:15] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:20] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:20] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:25] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:25] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:30] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:30] [INFO] Socket closed for 192.168.0.198:2004
[2025-05-06 16:07:40] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:45] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:50] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:07:55] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:08:00] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-06 16:08:11] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:08:16] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:08:21] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:08:26] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:08:31] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:08:56] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:09:01] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:09:19] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:09:24] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:09:29] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:09:57] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:03] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:07] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:13] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:17] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:22] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:27] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:32] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:37] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:10:42] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2002
[2025-05-06 16:16:39] [INFO] try to connect LSIS client 192.168.0.198:2004
[2025-05-06 16:16:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 16:17:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 16:18:03] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 16:18:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:11:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:13:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:14:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:17:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:19:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:19:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:19:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:20:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:26:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 17:36:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:21:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:22:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:23:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:24:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:24:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:25:33] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:25:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:26:03] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:26:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:26:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:26:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:31:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:31:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:36:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:37:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:39:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:52:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:54:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:55:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:55:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:55:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 18:59:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:01:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:04:13] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:04:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:04:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:05:13] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:05:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:06:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:07:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:07:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-06 19:08:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
